export class ConstantsMacros {
    static OpenGridMacroName = `OpenGridMacro`;
    static DoRelevanceSearchMacroName = `DoRelevanceSearchMacro`;
    static ResolveCaseMacroName = `ResolveCaseMacro`;
    static OpenKbArticleMacroName = `OpenKbArticleMacro`;
    static WebResourcesMacroName = `WebResourcesMacro`;
    static KBArticleMacroName = `KBArticleMacro`;
    static KBArticlelinkMacroName = `KBArticlelinkMacro`;
    static EntityRecordMacro = `EntityRecordMacro`;
    static SearchPhraseMacroName = `SearchPhraseMacro`;
    static RefreshMacroName = `RefreshMacro`;
    static LinkRecordMacroName = `LinkRecordMacro`;
    static UnlinkRecordMacroName = `UnlinkRecordMacro`;
    static TestMacro = "TestMacro";
    static CreateDraftEmailMacroName = `CreateDraftEmailMacro`;
    static OpenKBSearchMacroName = `OpenKBSearchMacro`;
    static SaveRecordAgentScriptName = `SaveRecordAgentScript`;
    static SaveRecordMacroName = `SaveRecordMacro`;
    static SaveRecordTitle = `//span[contains(.,'Automation Case')]`;
    static CloneRecordTitle = `//span[contains(.,'Automation Case')]`;
    static FocusTabAgentScriptName = `FocusTabAgentScript`;
    static FocusTabMacroName = `FocusTabMacro`;
    static FocusTabTitle = `//span[contains(.,'Automation Case')]`;
    static TabId = `//*[@aria-label="Tab ID"]`;
    static FocusApplicationTab = `//*[text()="Focus on the tab"]`; 
    static RadomNumberMin = 1000; 
    static RadomNumberMax = 9999;
    static Tab = `Tab`; 
    static EntityViewApplicationTab = `EntityViewApplicationTab`;
    static CloneInputAgentScriptName = `CloneInputAgentScript`;
    static CloneInputMacroName = `CloneInputMacro`;
    static CloneInputTitle = `//span[contains(.,'AutomationCase')]`;
    static CloneInputApplicationTab = `//*[text()="Clone input record"]`;
    static WebResourceTitle = `(//span[contains(.,'Automation Case')])`;
    static ExistingRecordTitle = `(//span[contains(.,'Automation Case')])`;
    static FailTitle =  `(//span[contains(.,'Automation Case')])`;
    static WebResourcesTitle =  `(//span[contains(.,'Automation Case')])`;
    static OpenKbArticleTitle =  `(//span[contains(.,'Automation Case')])`;
    static SearchPhraseTabName =  `(//span[contains(.,'Automation Case')])`;
    static RefreshTabTitle =  `(//span[contains(.,'Automation Case')])`;
    static ExistRecordTitleName =  `(//span[contains(.,'Automation Case')])`;
    static DoRelevanceSearchTitle =  `(//span[contains(.,'Automation Case')])`;
    static EntityViewName = `//span[text()='searchText']/following::div[@data-id="cell-0-3"]`;
    static WebResourceData = `//span[text()='data']/following::div[@data-id="cell-0-3"]`;
    static EntityListName = `//span[text()='entityName']/following::div[@data-id="cell-0-3"]`;
    static NameField = `//input[@data-id="msdyn_name.fieldControl-text-box-text"]`;
    static UniqueNameField = `//input[@data-id="msdyn_uniquename.fieldControl-text-box-text"]`;
    static PageTypeDropdown = `//select[@data-id="msdyn_pagetype.fieldControl-option-set-select"]`;
    static EntityListTitle =  `(//span[contains(.,'Automation Case')])`;
    static SearchTitle =  `(//span[contains(.,'Automation Case')])`;
    static ThirdPartyWebsiteTitle =  `(//span[contains(.,'Automation Case')])`;
    static ThirdPartyName = `//span[text()='data']/following::div[@data-id="cell-0-3"]`;
    static DashboardName = `//span[text()='dashboardId']/following::div[@data-id="cell-0-3"]`;
    static DashboardTitle =  `(//span[contains(.,'Automation Case')])`;
    static ControlTitle =  `(//span[contains(.,'Automation Case')])`;
}