//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Dynamics.SmartAssist.Plugin.Proxies
{
	/// <summary>
	/// Suggestions settings entity
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("msdyn_suggestionssetting")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.45")]
	public partial class msdyn_suggestionssetting : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{

		/// <summary>
		/// Default Constructor.
		/// </summary>
		public msdyn_suggestionssetting() :
				base(EntityLogicalName)
		{
		}

		public const string EntityLogicalName = "msdyn_suggestionssetting";

		public const int EntityTypeCode = 10142;

		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;

		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}

		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentidunique")]
		public System.Nullable<System.Guid> ComponentIdUnique
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("componentidunique");
			}
		}

		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentstate")]
		public Microsoft.Xrm.Sdk.OptionSetValue ComponentState
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("componentstate");
			}
		}

		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}

		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}

		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}

		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}

		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("iscustomizable")]
		public Microsoft.Xrm.Sdk.BooleanManagedProperty IsCustomizable
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.BooleanManagedProperty>("iscustomizable");
			}
			set
			{
				this.OnPropertyChanging("IsCustomizable");
				this.SetAttributeValue("iscustomizable", value);
				this.OnPropertyChanged("IsCustomizable");
			}
		}

		/// <summary>
		/// Indicates whether the solution component is part of a managed solution.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ismanaged")]
		public System.Nullable<bool> IsManaged
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("ismanaged");
			}
		}

		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}

		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}

		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}

		/// <summary>
		/// Case attribute which describes Issue Detail
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_casedetailmapping")]
		public string msdyn_CaseDetailMapping
		{
			get
			{
				return this.GetAttributeValue<string>("msdyn_casedetailmapping");
			}
			set
			{
				this.OnPropertyChanging("msdyn_CaseDetailMapping");
				this.SetAttributeValue("msdyn_casedetailmapping", value);
				this.OnPropertyChanged("msdyn_CaseDetailMapping");
			}
		}

		/// <summary>
		/// Case attribute which describes Issue Detail
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_casedetailmodelmapping")]
		public string msdyn_CaseDetailModelMapping
		{
			get
			{
				return this.GetAttributeValue<string>("msdyn_casedetailmodelmapping");
			}
			set
			{
				this.OnPropertyChanging("msdyn_CaseDetailModelMapping");
				this.SetAttributeValue("msdyn_casedetailmodelmapping", value);
				this.OnPropertyChanged("msdyn_CaseDetailModelMapping");
			}
		}

		/// <summary>
		/// Is Similar Case Suggestion Enabled for Case Entity. Default set is No.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_caseisenabled")]
		public System.Nullable<bool> msdyn_CaseIsEnabled
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("msdyn_caseisenabled");
			}
			set
			{
				this.OnPropertyChanging("msdyn_CaseIsEnabled");
				this.SetAttributeValue("msdyn_caseisenabled", value);
				this.OnPropertyChanged("msdyn_CaseIsEnabled");
			}
		}

		/// <summary>
		/// Case attribute which describes Issue Summary
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_casetitlemapping")]
		public string msdyn_CaseTitleMapping
		{
			get
			{
				return this.GetAttributeValue<string>("msdyn_casetitlemapping");
			}
			set
			{
				this.OnPropertyChanging("msdyn_CaseTitleMapping");
				this.SetAttributeValue("msdyn_casetitlemapping", value);
				this.OnPropertyChanged("msdyn_CaseTitleMapping");
			}
		}

		/// <summary>
		/// Case attribute which describes Issue Summary
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_casetitlemodelmapping")]
		public string msdyn_CaseTitleModelMapping
		{
			get
			{
				return this.GetAttributeValue<string>("msdyn_casetitlemodelmapping");
			}
			set
			{
				this.OnPropertyChanging("msdyn_CaseTitleModelMapping");
				this.SetAttributeValue("msdyn_casetitlemodelmapping", value);
				this.OnPropertyChanged("msdyn_CaseTitleModelMapping");
			}
		}

		/// <summary>
		/// Knowledge attribute which describes Issue Detail
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_kbcontentmapping")]
		public string msdyn_KBContentMapping
		{
			get
			{
				return this.GetAttributeValue<string>("msdyn_kbcontentmapping");
			}
			set
			{
				this.OnPropertyChanging("msdyn_KBContentMapping");
				this.SetAttributeValue("msdyn_kbcontentmapping", value);
				this.OnPropertyChanged("msdyn_KBContentMapping");
			}
		}

		/// <summary>
		/// Knowledge Content attribute mapping which describes Issue Detail and Training pipeline has used to generate model data.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_kbcontentmodelmapping")]
		public string msdyn_KBContentModelMapping
		{
			get
			{
				return this.GetAttributeValue<string>("msdyn_kbcontentmodelmapping");
			}
			set
			{
				this.OnPropertyChanging("msdyn_KBContentModelMapping");
				this.SetAttributeValue("msdyn_kbcontentmodelmapping", value);
				this.OnPropertyChanged("msdyn_KBContentModelMapping");
			}
		}

		/// <summary>
		/// Is Similar KB Suggestions is enabled. Default is No
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_kbisenabled")]
		public System.Nullable<bool> msdyn_KBIsEnabled
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("msdyn_kbisenabled");
			}
			set
			{
				this.OnPropertyChanging("msdyn_KBIsEnabled");
				this.SetAttributeValue("msdyn_kbisenabled", value);
				this.OnPropertyChanged("msdyn_KBIsEnabled");
			}
		}

		/// <summary>
		/// Knowledge attribute which describes Issue Summary
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_kbtitlemapping")]
		public string msdyn_KBTitleMapping
		{
			get
			{
				return this.GetAttributeValue<string>("msdyn_kbtitlemapping");
			}
			set
			{
				this.OnPropertyChanging("msdyn_KBTitleMapping");
				this.SetAttributeValue("msdyn_kbtitlemapping", value);
				this.OnPropertyChanged("msdyn_KBTitleMapping");
			}
		}

		/// <summary>
		/// Knowledge Title mapping attribute which used by training pipeline to generate model data.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_kbtitlemodelmapping")]
		public string msdyn_KBTitleModelMapping
		{
			get
			{
				return this.GetAttributeValue<string>("msdyn_kbtitlemodelmapping");
			}
			set
			{
				this.OnPropertyChanging("msdyn_KBTitleModelMapping");
				this.SetAttributeValue("msdyn_kbtitlemodelmapping", value);
				this.OnPropertyChanged("msdyn_KBTitleModelMapping");
			}
		}

		/// <summary>
		/// The name of the custom entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_name")]
		public string msdyn_name
		{
			get
			{
				return this.GetAttributeValue<string>("msdyn_name");
			}
			set
			{
				this.OnPropertyChanging("msdyn_name");
				this.SetAttributeValue("msdyn_name", value);
				this.OnPropertyChanged("msdyn_name");
			}
		}

		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_suggestionssettingid")]
		public System.Nullable<System.Guid> msdyn_suggestionssettingId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("msdyn_suggestionssettingid");
			}
			set
			{
				this.OnPropertyChanging("msdyn_suggestionssettingId");
				this.SetAttributeValue("msdyn_suggestionssettingid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("msdyn_suggestionssettingId");
			}
		}

		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_suggestionssettingid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.msdyn_suggestionssettingId = value;
			}
		}

		/// <summary>
		/// Unique identifier for the organization
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
		public Microsoft.Xrm.Sdk.EntityReference OrganizationId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("organizationid");
			}
		}

		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}

		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overwritetime")]
		public System.Nullable<System.DateTime> OverwriteTime
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overwritetime");
			}
		}

		/// <summary>
		/// Unique identifier of the associated solution.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutionid")]
		public System.Nullable<System.Guid> SolutionId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("solutionid");
			}
		}

		/// <summary>
		/// Status of the suggestionssetting
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public System.Nullable<Microsoft.Dynamics.SmartAssist.Plugin.Proxies.msdyn_suggestionssettingState> statecode
		{
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((Microsoft.Dynamics.SmartAssist.Plugin.Proxies.msdyn_suggestionssettingState)(System.Enum.ToObject(typeof(Microsoft.Dynamics.SmartAssist.Plugin.Proxies.msdyn_suggestionssettingState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			set
			{
				this.OnPropertyChanging("statecode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("statecode");
			}
		}

		/// <summary>
		/// Reason for the status of the suggestionssetting
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue statuscode
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
			}
			set
			{
				this.OnPropertyChanging("statuscode");
				this.SetAttributeValue("statuscode", value);
				this.OnPropertyChanged("statuscode");
			}
		}

		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}

		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}

		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
	}
}