//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Dynamics.CIFramework.WebResources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CIF_webresource_strings_1033 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CIF_webresource_strings_1033() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Dynamics.CIFramework.WebResources.Localization.CIF_webresource_strings." +
                            "1033", typeof(CIF_webresource_strings_1033).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string ACCEPT_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("ACCEPT_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add note.
        /// </summary>
        internal static string ADD_NOTE_TEXT {
            get {
                return ResourceManager.GetString("ADD_NOTE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Image.
        /// </summary>
        internal static string AGENT_IMAGE_ALT_TEXT {
            get {
                return ResourceManager.GetString("AGENT_IMAGE_ALT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CANCEL_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("CANCEL_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CLOSE_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("CLOSE_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch presence dialog.
        /// </summary>
        internal static string LAUNCH_PRESENCE_DIALOG_TOOLTIP {
            get {
                return ResourceManager.GetString("LAUNCH_PRESENCE_DIALOG_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Notes.
        /// </summary>
        internal static string NOTES_TOOLTIP_TEXT {
            get {
                return ResourceManager.GetString("NOTES_TOOLTIP_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string NOTIFICATION_DETAIL_COMMENT_TEXT {
            get {
                return ResourceManager.GetString("NOTIFICATION_DETAIL_COMMENT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait time.
        /// </summary>
        internal static string NOTIFICATION_DETAIL_WAIT_TIME_TEXT {
            get {
                return ResourceManager.GetString("NOTIFICATION_DETAIL_WAIT_TIME_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to secs.
        /// </summary>
        internal static string NOTIFICATION_WAIT_TIME_SECONDS {
            get {
                return ResourceManager.GetString("NOTIFICATION_WAIT_TIME_SECONDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Item.
        /// </summary>
        internal static string OPEN_ITEM_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("OPEN_ITEM_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string PRESENCE_AVAILABLE_TEXT {
            get {
                return ResourceManager.GetString("PRESENCE_AVAILABLE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away.
        /// </summary>
        internal static string PRESENCE_AWAY_TEXT {
            get {
                return ResourceManager.GetString("PRESENCE_AWAY_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busy.
        /// </summary>
        internal static string PRESENCE_BUSY_TEXT {
            get {
                return ResourceManager.GetString("PRESENCE_BUSY_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presence.
        /// </summary>
        internal static string PRESENCE_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("PRESENCE_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do Not Disturb.
        /// </summary>
        internal static string PRESENCE_DO_NOT_DISTURB_TEXT {
            get {
                return ResourceManager.GetString("PRESENCE_DO_NOT_DISTURB_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string PRESENCE_OFFLINE_TEXT {
            get {
                return ResourceManager.GetString("PRESENCE_OFFLINE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string PRESENCE_UNKOWN_TEXT {
            get {
                return ResourceManager.GetString("PRESENCE_UNKOWN_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        internal static string REJECT_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("REJECT_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start adding notes.
        /// </summary>
        internal static string START_NOTES_TOOLTIP_TEXT {
            get {
                return ResourceManager.GetString("START_NOTES_TOOLTIP_TEXT", resourceCulture);
            }
        }
    }
}
