//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Dynamics.CIFramework.WebResources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CIF_webresource_strings_1033 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CIF_webresource_strings_1033() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Dynamics.CIFramework.WebResources.Localization.CIF_webresource_strings." +
                            "1033", typeof(CIF_webresource_strings_1033).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string ACCEPT_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("ACCEPT_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add note.
        /// </summary>
        internal static string ADD_NOTE_TEXT {
            get {
                return ResourceManager.GetString("ADD_NOTE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Image.
        /// </summary>
        internal static string AGENT_IMAGE_ALT_TEXT {
            get {
                return ResourceManager.GetString("AGENT_IMAGE_ALT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CANCEL_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("CANCEL_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CLOSE_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("CLOSE_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View and access all the customer information at your fingertips at one place to deliver a faster service..
        /// </summary>
        internal static string FRE_COMPREHENSIVEVIEW_DESC {
            get {
                return ResourceManager.GetString("FRE_COMPREHENSIVEVIEW_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprehensive view of your customers&apos; journey.
        /// </summary>
        internal static string FRE_COMPREHENSIVEVIEW_TITLE {
            get {
                return ResourceManager.GetString("FRE_COMPREHENSIVEVIEW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite other agents, supervisors to collaborate and solve the issues faster..
        /// </summary>
        internal static string FRE_CONSULT_DESC {
            get {
                return ResourceManager.GetString("FRE_CONSULT_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consult with users.
        /// </summary>
        internal static string FRE_CONSULT_TITLE {
            get {
                return ResourceManager.GetString("FRE_CONSULT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access and manage sitemap applications that lie within the context of a session..
        /// </summary>
        internal static string FRE_CONTEXTUALAPPS_DESC {
            get {
                return ResourceManager.GetString("FRE_CONTEXTUALAPPS_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contextual applications.
        /// </summary>
        internal static string FRE_CONTEXTUALAPPS_TITLE {
            get {
                return ResourceManager.GetString("FRE_CONTEXTUALAPPS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t show me again.
        /// </summary>
        internal static string FRE_DONTSHOWMEAGAIN {
            get {
                return ResourceManager.GetString("FRE_DONTSHOWMEAGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quickly open work items with keyboard and mouse-click gesture and maximize your productivity..
        /// </summary>
        internal static string FRE_GETMOREDONE_DESC {
            get {
                return ResourceManager.GetString("FRE_GETMOREDONE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get more done.
        /// </summary>
        internal static string FRE_GETMOREDONE_TITLE {
            get {
                return ResourceManager.GetString("FRE_GETMOREDONE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        internal static string FRE_GETSTARTED {
            get {
                return ResourceManager.GetString("FRE_GETSTARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a quick tour to learn how to deliver fast, personalized service to your customers..
        /// </summary>
        internal static string FRE_INTRO_SLIDE_DESC {
            get {
                return ResourceManager.GetString("FRE_INTRO_SLIDE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Omnichannel for Dynamics 365 Customer Service.
        /// </summary>
        internal static string FRE_INTRO_SLIDE_TITLE {
            get {
                return ResourceManager.GetString("FRE_INTRO_SLIDE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Done.
        /// </summary>
        internal static string FRE_LASTSLIDE_TITLE {
            get {
                return ResourceManager.GetString("FRE_LASTSLIDE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        internal static string FRE_PAGINATION_OF {
            get {
                return ResourceManager.GetString("FRE_PAGINATION_OF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer the conversations smoothly to the best-qualified agents to resolve them fast..
        /// </summary>
        internal static string FRE_TRANSFER_DESC {
            get {
                return ResourceManager.GetString("FRE_TRANSFER_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer the conversation.
        /// </summary>
        internal static string FRE_TRANSFER_TITLE {
            get {
                return ResourceManager.GetString("FRE_TRANSFER_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage multiple customer conversations simultaneously with complete control of the context and customer details..
        /// </summary>
        internal static string FRE_WORKWITHMULTIPLE_DESC {
            get {
                return ResourceManager.GetString("FRE_WORKWITHMULTIPLE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work with multiple customers.
        /// </summary>
        internal static string FRE_WORKWITHMULTIPLE_TITLE {
            get {
                return ResourceManager.GetString("FRE_WORKWITHMULTIPLE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch presence dialog.
        /// </summary>
        internal static string LAUNCH_PRESENCE_DIALOG_TOOLTIP {
            get {
                return ResourceManager.GetString("LAUNCH_PRESENCE_DIALOG_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh the tab..
        /// </summary>
        internal static string msdyn_macroactiontemplate_msdyn_actionDescription_48fc87c4_f480_4129_9c1d_682442d7bc60 {
            get {
                return ResourceManager.GetString("msdyn_macroactiontemplate_msdyn_actionDescription_48fc87c4_f480_4129_9c1d_682442d" +
                        "7bc60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus tab..
        /// </summary>
        internal static string msdyn_macroactiontemplate_msdyn_actionDescription_761589d3_4fd7_4cab_b2f7_96728d4b9823 {
            get {
                return ResourceManager.GetString("msdyn_macroactiontemplate_msdyn_actionDescription_761589d3_4fd7_4cab_b2f7_96728d4" +
                        "b9823", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the current page..
        /// </summary>
        internal static string msdyn_macroactiontemplate_msdyn_actionDescription_d3ee390f_0299_43e5_8107_e637feeb170d {
            get {
                return ResourceManager.GetString("msdyn_macroactiontemplate_msdyn_actionDescription_d3ee390f_0299_43e5_8107_e637fee" +
                        "b170d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh the tab.
        /// </summary>
        internal static string msdyn_macroactiontemplate_msdyn_displayname_48fc87c4_f480_4129_9c1d_682442d7bc60 {
            get {
                return ResourceManager.GetString("msdyn_macroactiontemplate_msdyn_displayname_48fc87c4_f480_4129_9c1d_682442d7bc60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus tab.
        /// </summary>
        internal static string msdyn_macroactiontemplate_msdyn_displayname_761589d3_4fd7_4cab_b2f7_96728d4b9823 {
            get {
                return ResourceManager.GetString("msdyn_macroactiontemplate_msdyn_displayname_761589d3_4fd7_4cab_b2f7_96728d4b9823", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the current page.
        /// </summary>
        internal static string msdyn_macroactiontemplate_msdyn_displayname_d3ee390f_0299_43e5_8107_e637feeb170d {
            get {
                return ResourceManager.GetString("msdyn_macroactiontemplate_msdyn_displayname_d3ee390f_0299_43e5_8107_e637feeb170d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session connector.
        /// </summary>
        internal static string msdyn_macroactiontemplate_msdyn_subtitle_48fc87c4_f480_4129_9c1d_682442d7bc60 {
            get {
                return ResourceManager.GetString("msdyn_macroactiontemplate_msdyn_subtitle_48fc87c4_f480_4129_9c1d_682442d7bc60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session connector.
        /// </summary>
        internal static string msdyn_macroactiontemplate_msdyn_subtitle_761589d3_4fd7_4cab_b2f7_96728d4b9823 {
            get {
                return ResourceManager.GetString("msdyn_macroactiontemplate_msdyn_subtitle_761589d3_4fd7_4cab_b2f7_96728d4b9823", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session connector.
        /// </summary>
        internal static string msdyn_macroactiontemplate_msdyn_subtitle_d3ee390f_0299_43e5_8107_e637feeb170d {
            get {
                return ResourceManager.GetString("msdyn_macroactiontemplate_msdyn_subtitle_d3ee390f_0299_43e5_8107_e637feeb170d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh the tab.
        /// </summary>
        internal static string msdyn_macroactiontemplate_msdyn_summary_48fc87c4_f480_4129_9c1d_682442d7bc60 {
            get {
                return ResourceManager.GetString("msdyn_macroactiontemplate_msdyn_summary_48fc87c4_f480_4129_9c1d_682442d7bc60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus tab.
        /// </summary>
        internal static string msdyn_macroactiontemplate_msdyn_summary_761589d3_4fd7_4cab_b2f7_96728d4b9823 {
            get {
                return ResourceManager.GetString("msdyn_macroactiontemplate_msdyn_summary_761589d3_4fd7_4cab_b2f7_96728d4b9823", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the current page.
        /// </summary>
        internal static string msdyn_macroactiontemplate_msdyn_summary_d3ee390f_0299_43e5_8107_e637feeb170d {
            get {
                return ResourceManager.GetString("msdyn_macroactiontemplate_msdyn_summary_d3ee390f_0299_43e5_8107_e637feeb170d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh the tab.
        /// </summary>
        internal static string msdyn_macroactiontemplate_msdyn_title_48fc87c4_f480_4129_9c1d_682442d7bc60 {
            get {
                return ResourceManager.GetString("msdyn_macroactiontemplate_msdyn_title_48fc87c4_f480_4129_9c1d_682442d7bc60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus tab.
        /// </summary>
        internal static string msdyn_macroactiontemplate_msdyn_title_761589d3_4fd7_4cab_b2f7_96728d4b9823 {
            get {
                return ResourceManager.GetString("msdyn_macroactiontemplate_msdyn_title_761589d3_4fd7_4cab_b2f7_96728d4b9823", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the current page.
        /// </summary>
        internal static string msdyn_macroactiontemplate_msdyn_title_d3ee390f_0299_43e5_8107_e637feeb170d {
            get {
                return ResourceManager.GetString("msdyn_macroactiontemplate_msdyn_title_d3ee390f_0299_43e5_8107_e637feeb170d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predefined automation actions.
        /// </summary>
        internal static string msdyn_macroconnector_msdyn_categorylabel_ac627bea_31f2_4378_9a21_6e1e2d74e278 {
            get {
                return ResourceManager.GetString("msdyn_macroconnector_msdyn_categorylabel_ac627bea_31f2_4378_9a21_6e1e2d74e278", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automate commonly used session actions.
        /// </summary>
        internal static string msdyn_macroconnector_msdyn_description_ac627bea_31f2_4378_9a21_6e1e2d74e278 {
            get {
                return ResourceManager.GetString("msdyn_macroconnector_msdyn_description_ac627bea_31f2_4378_9a21_6e1e2d74e278", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Connector.
        /// </summary>
        internal static string msdyn_macroconnector_msdyn_displayname_ac627bea_31f2_4378_9a21_6e1e2d74e278 {
            get {
                return ResourceManager.GetString("msdyn_macroconnector_msdyn_displayname_ac627bea_31f2_4378_9a21_6e1e2d74e278", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Connector.
        /// </summary>
        internal static string msdyn_macroconnector_msdyn_title_ac627bea_31f2_4378_9a21_6e1e2d74e278 {
            get {
                return ResourceManager.GetString("msdyn_macroconnector_msdyn_title_ac627bea_31f2_4378_9a21_6e1e2d74e278", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Notes.
        /// </summary>
        internal static string NOTES_TOOLTIP_TEXT {
            get {
                return ResourceManager.GetString("NOTES_TOOLTIP_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string NOTIFICATION_DETAIL_COMMENT_TEXT {
            get {
                return ResourceManager.GetString("NOTIFICATION_DETAIL_COMMENT_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait time.
        /// </summary>
        internal static string NOTIFICATION_DETAIL_WAIT_TIME_TEXT {
            get {
                return ResourceManager.GetString("NOTIFICATION_DETAIL_WAIT_TIME_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to secs.
        /// </summary>
        internal static string NOTIFICATION_WAIT_TIME_SECONDS {
            get {
                return ResourceManager.GetString("NOTIFICATION_WAIT_TIME_SECONDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Item.
        /// </summary>
        internal static string OPEN_ITEM_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("OPEN_ITEM_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string PRESENCE_AVAILABLE_TEXT {
            get {
                return ResourceManager.GetString("PRESENCE_AVAILABLE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away.
        /// </summary>
        internal static string PRESENCE_AWAY_TEXT {
            get {
                return ResourceManager.GetString("PRESENCE_AWAY_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busy.
        /// </summary>
        internal static string PRESENCE_BUSY_TEXT {
            get {
                return ResourceManager.GetString("PRESENCE_BUSY_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presence.
        /// </summary>
        internal static string PRESENCE_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("PRESENCE_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do Not Disturb.
        /// </summary>
        internal static string PRESENCE_DO_NOT_DISTURB_TEXT {
            get {
                return ResourceManager.GetString("PRESENCE_DO_NOT_DISTURB_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string PRESENCE_OFFLINE_TEXT {
            get {
                return ResourceManager.GetString("PRESENCE_OFFLINE_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string PRESENCE_UNKOWN_TEXT {
            get {
                return ResourceManager.GetString("PRESENCE_UNKOWN_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        internal static string REJECT_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("REJECT_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start adding notes.
        /// </summary>
        internal static string START_NOTES_TOOLTIP_TEXT {
            get {
                return ResourceManager.GetString("START_NOTES_TOOLTIP_TEXT", resourceCulture);
            }
        }
    }
}
